inherit_from: .rubocop_todo.yml
require:
  - rubocop/cop/internal_affairs

Metrics/BlockLength:
  Exclude:
    # Exclude the spec directory because the rspec DSL results in long blocks
    - 'spec/**/*'
